export const loanSchemes = [
  {
    bank: "SBI",
    scheme: "SBI Student Loan Scheme",
    studyLocation: "india_abroad", // both covered
    maxAmount: 2000000, // ₹20 lakh for abroad
    interestRate: 11.15,
    collateralRequired: true, // required above ₹7.5 lakh
    coBorrowerRequired: true,
  },
  {
    bank: "SBI",
    scheme: "SBI Scholar Loan Scheme",
    studyLocation: "india", // only premier Indian institutions
    maxAmount: 4000000, // ₹40 lakh for List AA
    interestRate: 8.10,
    collateralRequired: true, // required above ₹7.5 lakh
    coBorrowerRequired: true,
  },
  {
    bank: "SBI",
    scheme: "SBI Skill Loan Scheme",
    studyLocation: "india",
    maxAmount: 150000,
    interestRate: 10.65,
    collateralRequired: false,
    coBorrowerRequired: true,
  },
  {
    bank: "SBI",
    scheme: "SBI Global Ed-Vantage Scheme",
    studyLocation: "outside_india",
    maxAmount: 15000000,
    interestRate: 11.15,
    collateralRequired: true,
    coBorrowerRequired: true,
  },
  {
    bank: "Bank of Baroda",
    scheme: "Baroda Vidya",
    studyLocation: "india",
    maxAmount: 400000,
    interestRate: 12.5,
    collateralRequired: false,
    coBorrowerRequired: true,
  },
  {
    bank: "Bank of Baroda",
    scheme: "Baroda Gyan",
    studyLocation: "india",
    maxAmount: 2500000,
    interestRate: 11.1,
    collateralRequired: true,
    coBorrowerRequired: true,
  },
  {
    bank: "Bank of Baroda",
    scheme: "Baroda Scholar",
    studyLocation: "outside_india",
    maxAmount: 15000000,
    interestRate: 10.4,
    collateralRequired: true,
    coBorrowerRequired: true,
  },
  {
    bank: "Bank of Baroda",
    scheme: "Baroda Education Loan to Students of Premier Institutions",
    studyLocation: "india",
    maxAmount: 8000000,
    interestRate: 9.05,
    collateralRequired: true,
    coBorrowerRequired: true,
  },
  {
    bank: "Bank of Baroda",
    scheme: "Baroda Skill Loan Scheme",
    studyLocation: "india",
    maxAmount: 150000,
    interestRate: 10.65,
    collateralRequired: false,
    coBorrowerRequired: true,
  },
  {
    bank: "ICICI Bank",
    scheme: "ICICI Bank Education Loan",
    studyLocation: "both",
    maxAmount: 30000000,
    interestRate: 11.15,
    collateralRequired: true,
    coBorrowerRequired: true,
  },
  {
    bank: "Axis Bank",
    scheme: "Axis Bank Education Loan",
    studyLocation: "both",
    maxAmount: 2000000,
    interestRate: 14.45,
    collateralRequired: true,
    coBorrowerRequired: true,
  },
  {
    bank: "PNB",
    scheme: "PNB Saraswati",
    studyLocation: "both",
    maxAmount: 5000000,
    interestRate: 11.0,
    collateralRequired: true,
    coBorrowerRequired: true,
  },
  {
    bank: "Bank of Maharashtra",
    scheme: "Skill Loan Scheme",
    studyLocation: "india",
    maxAmount: 150000,
    interestRate: 11.05,
    collateralRequired: false,
    coBorrowerRequired: true,
  },
  {
    bank: "Bank of Maharashtra",
    scheme: "Vidya Lakshmi Education Loan Scheme",
    studyLocation: "both",
    maxAmount: 2000000,
    interestRate: 11.05,
    collateralRequired: true,
    coBorrowerRequired: true,
  },
  {
    bank: "Bank of India",
    scheme: "Star Pradhanmantri Kaushal Rin Yojana",
    studyLocation: "india",
    maxAmount: 150000,
    interestRate: 12.2,
    collateralRequired: false,
    coBorrowerRequired: true,
  }
  ];
  